name: Lint YAML Files

description: A composite action for linting YAML files.

inputs:
  python-version:
    description: The version of Python to use when running `yamllint`.
    default: 3.14.2
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install yamllint
      run: |
        pip install --upgrade pip
        pip install yamllint

    - name: Lint YAML Files
      run: |-
        yamllint .
