name: Lint

on: pull_request

permissions:
  contents: read

jobs:
  actionlint:
    name: GitHub Actions
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint Workflow Files
        uses: craigsloggett/lint-github-actions-workflows@9daa91441aac2bd980998d791e1ee105b7786d64 # v1.0.4

  yamllint:
    name: YAML
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint YAML Files
        uses: craigsloggett/lint-yaml@ee49d22bec6c5d0b0d8e2c4774a1f172b0483b35 # v1.0.20
